title: Mujeres en Tecnología
description: >-
  Mujeres en tecnología es una mesa de trabajo abierta, diversa e inclusiva, para 
  personas e instituciones que quieran apoyar la participación femenina en las 
  ciencias y en la industria tecnológica, que busca consolidar, visibilizar, 
  potenciar y ampliar iniciativas pro mujeres en tecnología.
baseurl: "/home"
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
environment: dev
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
