title: Mujeres en Tecnología
description: >-
  Mujeres en Tecnología es un sitio web para la difusión de información y eventos sobre personas e 
  instituciones que apoyan la participación femenina en las ciencias y en la industria tecnológica en Chile.
url: "https://mujeresentecnologia.github.io"


markdown: kramdown
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - README.md
  - INSTALL.md
  - LICENSE
  - NOTICE

# Config overriten in staging
baseurl: "/home"
google_analytics: UA-111563968-1
environment: prod
hotjar_id: 767992